# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Morning Data
paginate:       5
baseurl:        ""
url:            "mubaris.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Mubaris NK
  url:          http://mubaris.com
  email:        mubarishassannk@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/mubaris/mubaris.github.io

# Plugins
gems:
  - jekyll-paginate
