# Site settings
title: Mubaris' Blog
SEOTitle: Mubaris' Blog
header-img: img/home-bg.jpg
email: mubarishassannk@gmail.com
description: "Exploring Machine Learning and Data Science"
keyword: "Python, Mubaris, Blog, Machine Learning, Data Science, Data Visualization, R, Julia, ML, AI, DataViz"
url: "https://mubaris.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
facebook_username:     nk.mubaris
linkedin_username:     mubaris-nk
github_username:    mubaris
twitter_username:   Mubaris_NK
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: morning-data

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-93985002-1'            # Format: UA-xxxxxx-xx
ga_domain: mubaris.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Data Scientist and Full Stack Developer"
sidebar-avatar: /img/avatar-hux.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# plugins:
#   - jekyll-paginate
#   - jekyll-seo-tag
#   - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username:     Mubaris_NK

author:
  name:         Mubaris NK
  url:          https://mubaris.com
  email:        mubarishassannk@gmail.com

# # Friends
# friends: [
#     {
#     #     title: "Su",
#     #     href: "http://su.gallery/"
#     # },{
#         title: "乱序",
#         href: "http://mida.re/"
#     },{
#         title: "前端外刊评论",
#         href: "http://qianduan.guru/"
#     },{
#         title: "天镶的博客",
#         href: "http://lingyu.wang/"
#     },{
#         title: "Luke 的自留地",
#         href: "http://hmqk1995.github.io"
#     },{
#         title: "Ebn's Blog",
#         href: "http://ebnbin.com/"
#     },{
#         title: "SmdCn's Blog",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "解旻的博客",
#         href: "http://xieminis.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
#         title: "尹峰以为",
#         href: "http://ingf.github.io/"
#     },{
#         title: "前端神盾局",
#         href: "http://wepiaofei.github.io/blog/"
#     }
# ]

permalink:      /:year-:month-:day/:title