# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Mubaris NK
description:    Exploring Machine Learning and Data Science
paginate:       5
baseurl:        ""
url:            https://mubaris.com

twitter:
  username:     MubarisHassan

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Mubaris NK
  url:          https://mubaris.com
  email:        mubarishassannk@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/mubaris/website

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
